soc:
	../../soc/python/soc.py --design ./design.json --mode verilog --database add
soc_macro:
	../../soc/python/soc.py --design ./design.json --mode macro --database add
soc_full:
	../../soc/python/soc.py --design ./design.json --mode full --database add
clean:
	../../soc/python/clean.py --design ./design.json --connection remove