//******************************************************************************
//*
//* Generated by      : Arm (R) Socrates (TM)
//*
//* Generator version : 18.1.0.0
//*
//* Generation time   : 2019.7.12 15:25
//*
//* Filename          : design_test_2.v
//*
//* Component name    : design_test_2
//*
//* Component version : r0p0
//*
//******************************************************************************




module design_test_2
(
);


ldo-gen i_ldo2
  (
    .PCLK (),
    .reset ()
  );

memory-gen i_mem2
  (
    .PCLK (),
    .PRESETN (),
    .PCLKEN (),
    .PSEL (),
    .PADDR (),
    .PENABLE (),
    .PWRITE (),
    .PWDATA (),
    .PRDATA (),
    .PREADY (),
    .PSLVERR (),
    .CLK_SRAM_IN (),
    .DATA_REQ_SRAM_IN (),
    .WE_SRAM_IN (),
    .DATA_BE_SRAM_IN (),
    .ADDR_SRAM_IN (),
    .DATA_SRAM_IN (),
    .DATA_SRAM_OUT ()
  );

pll-gen i_pll2
  (
    .PCLK (),
    .PRESETn (),
    .PCLKEN (),
    .PSEL (),
    .PADDR (),
    .PENABLE (),
    .PWRITE (),
    .PWDATA (),
    .PRDATA (),
    .PREADY (),
    .PSLVERR (),
    .CLK_OUT ()
  );

temp-sense-gen i_temp_sense2
  (
    .PCLK (),
    .PRESETN (),
    .PCLKEN (),
    .PSEL (),
    .PADDR (),
    .PENABLE (),
    .PWRITE (),
    .PWDATA (),
    .PRDATA (),
    .PREADY (),
    .PSLVERR (),
    .CLK_REF (),
    .enable (),
    .RESET_COUNTERn (),
    .SEL_CONV_TIME (),
    .DOUT (),
    .DONE (),
    .out0 (),
    .outb (),
    .lcout ()
  );

cmsdk_apb_slave_mux_rtl u_apb_slave_mux2
  (
    .DECODE4BIT (),
    .PSEL (),
    .PSEL0 (),
    .PREADY0 (),
    .PRDATA0 (),
    .PSLVERR0 (),
    .PSEL1 (),
    .PREADY1 (),
    .PRDATA1 (),
    .PSLVERR1 (),
    .PSEL2 (),
    .PREADY2 (),
    .PRDATA2 (),
    .PSLVERR2 (),
    .PSEL3 (),
    .PREADY3 (),
    .PRDATA3 (),
    .PSLVERR3 (),
    .PSEL4 (),
    .PREADY4 (),
    .PRDATA4 (),
    .PSLVERR4 (),
    .PSEL5 (),
    .PREADY5 (),
    .PRDATA5 (),
    .PSLVERR5 (),
    .PSEL6 (),
    .PREADY6 (),
    .PRDATA6 (),
    .PSLVERR6 (),
    .PSEL7 (),
    .PREADY7 (),
    .PRDATA7 (),
    .PSLVERR7 (),
    .PSEL8 (),
    .PREADY8 (),
    .PRDATA8 (),
    .PSLVERR8 (),
    .PSEL9 (),
    .PREADY9 (),
    .PRDATA9 (),
    .PSLVERR9 (),
    .PSEL10 (),
    .PREADY10 (),
    .PRDATA10 (),
    .PSLVERR10 (),
    .PSEL11 (),
    .PREADY11 (),
    .PRDATA11 (),
    .PSLVERR11 (),
    .PSEL12 (),
    .PREADY12 (),
    .PRDATA12 (),
    .PSLVERR12 (),
    .PSEL13 (),
    .PREADY13 (),
    .PRDATA13 (),
    .PSLVERR13 (),
    .PSEL14 (),
    .PREADY14 (),
    .PRDATA14 (),
    .PSLVERR14 (),
    .PSEL15 (),
    .PREADY15 (),
    .PRDATA15 (),
    .PSLVERR15 (),
    .PREADY (),
    .PRDATA (),
    .PSLVERR ()
  );

cmsdk_ahb_to_apb_rtl u_ahb_to_apb2
  (
    .HCLK (),
    .HRESETn (),
    .PCLKEN (),
    .HSEL (),
    .HADDR (),
    .HTRANS (),
    .HSIZE (),
    .HPROT (),
    .HWRITE (),
    .HREADY (),
    .HWDATA (),
    .HREADYOUT (),
    .HRDATA (),
    .HRESP (),
    .PADDR (),
    .PENABLE (),
    .PWRITE (),
    .PSTRB (),
    .PPROT (),
    .PWDATA (),
    .PSEL (),
    .APBACTIVE (),
    .PRDATA (),
    .PREADY (),
    .PSLVERR ()
  );

fasoc_m0mcu_rtl i_fasoc_m0mcu2
  (
    .XTAL1 (),
    .XTAL2 (),
    .NRST (),
    .P0 (),
    .P1 (),
    .nTRST (),
    .TDI (),
    .TDO (),
    .SWDIOTMS (),
    .SWCLKTCK (),
    .ext_HCLK (),
    .ext_HRESETn (),
    .ext_HSEL (),
    .ext_HADDR (),
    .ext_HTRANS (),
    .ext_HWRITE (),
    .ext_HSIZE (),
    .ext_HPROT (),
    .ext_HREADY (),
    .ext_HWDATA (),
    .ext_HREADYOUT (),
    .ext_HRDATA (),
    .ext_HRESP (),
    .PRESETn (),
    .PCLK (),
    .PCLKG (),
    .APBACTIVE (),
    .PCLKEN ()
  );



endmodule
