//******************************************************************************
//*
//* Generated by      : Arm (R) Socrates (TM)
//*
//* Generator version : 18.1.0.0
//*
//* Generation time   : 2019.7.7 13:6
//*
//* Filename          : fasoc_test8.v
//*
//* Component name    : fasoc_test8
//*
//* Component version : r0p0
//*
//******************************************************************************




module fasoc_test8
(
  // Unmapped ports
  input          XTAL1                                             ,
  output         XTAL2                                             ,
  input          nTRST                                             ,
  inout  [15:0]  P0                                                ,
  inout  [15:0]  P1                                                ,
  inout          SWDIOTMS                                          ,
  input          SWCLKTCK                                          ,
  output         SYSCLKOUT                                         ,
  output         SYSCLK                                            ,
  input          SYSRESETN                                         
);

wire         _XTAL1_w;
wire         _nTRST_w;
wire         _SWCLKTCK_w;
wire         _SYSRESETN_w;
wire         _XTAL2_w;
wire         _SYSCLKOUT_w;
wire         _SYSCLK_w;
wire         i_fasoc_m0mcu2_XTAL2_w;
wire         i_fasoc_m0mcu2_ext_HBURST_w;
wire [15:0]  i_fasoc_m0mcu2_ext_HADDR_w;
wire [1:0]   i_fasoc_m0mcu2_ext_HTRANS_w;
wire         i_fasoc_m0mcu2_ext_HWRITE_w;
wire [2:0]   i_fasoc_m0mcu2_ext_HSIZE_w;
wire [3:0]   i_fasoc_m0mcu2_ext_HPROT_w;
wire         i_fasoc_m0mcu2_ext_HREADY_w;
wire [31:0]  i_fasoc_m0mcu2_ext_HWDATA_w;
wire         i_fasoc_m0mcu2_PCLKEN_w;
wire [31:0]  i_mem2_prdata_w;
wire         i_mem2_pready_w;
wire         i_mem2_pslverr_w;
wire [31:0]  i_pll2_PRDATA_w;
wire         i_pll2_PREADY_w;
wire         i_pll2_PSLVERR_w;
wire         i_pll2_CLKOUT_w;
wire [11:0]  i_pll2_PADDR_w;
wire [31:0]  i_temp_sense2_PRDATA_w;
wire         i_temp_sense2_PREADY_w;
wire         i_temp_sense2_PSLVERR_w;
wire [3:0]   i_temp_sense2_PADDR_w;
wire [31:0]  u_ahb_to_apb2_HRDATA_w;
wire         u_ahb_to_apb2_HRESP_w;
wire [15:0]  u_ahb_to_apb2_PADDR_w;
wire         u_ahb_to_apb2_PENABLE_w;
wire         u_ahb_to_apb2_PWRITE_w;
wire [31:0]  u_ahb_to_apb2_PWDATA_w;
wire         u_ahb_to_apb2_PSEL_w;
wire         u_ahb_to_apb2_APBACTIVE_w;
wire         u_apb_slave_mux2_PSEL4_w;
wire         u_apb_slave_mux2_PSEL5_w;
wire         u_apb_slave_mux2_PSEL6_w;
wire         u_apb_slave_mux2_PREADY_w;
wire [31:0]  u_apb_slave_mux2_PRDATA_w;
wire         u_apb_slave_mux2_PSLVERR_w;

ldo-gen i_ldo2
  (
    .PCLK (i_fasoc_m0mcu2_ext_HCLK_w),                            // 
    .reset (i_fasoc_m0mcu2_ext_HRESETn_w)                            // 
  );

memory-gen i_mem2
  (
    .pclk (i_fasoc_m0mcu2_ext_HCLK_w),                            // 
    .presetn (i_fasoc_m0mcu2_ext_HRESETn_w),                            // 
    .psel (u_apb_slave_mux2_PSEL4_w),                            // 
    .paddr (u_ahb_to_apb2_PADDR_w[3:0]),                            // 
    .penable (u_ahb_to_apb2_PENABLE_w),                            // 
    .pwrite (u_ahb_to_apb2_PWRITE_w),                            // 
    .pwdata (u_ahb_to_apb2_PWDATA_w[31:0]),                            // 
    .prdata (i_mem2_prdata_w),                            // 
    .pready (i_mem2_pready_w),                            // 
    .pslverr (i_mem2_pslverr_w)                            // 
  );

pll-gen i_pll2
  (
    .PCLK (i_fasoc_m0mcu2_ext_HCLK_w),                            // 
    .PRESETn (i_fasoc_m0mcu2_ext_HRESETn_w),                            // 
    .PSEL (u_apb_slave_mux2_PSEL5_w),                            // 
    .PADDR (i_pll2_PADDR_w),                            // 
    .PENABLE (u_ahb_to_apb2_PENABLE_w),                            // 
    .PWRITE (u_ahb_to_apb2_PWRITE_w),                            // 
    .PWDATA (u_ahb_to_apb2_PWDATA_w[31:0]),                            // 
    .PRDATA (i_pll2_PRDATA_w),                            // 
    .PREADY (i_pll2_PREADY_w),                            // 
    .PSLVERR (i_pll2_PSLVERR_w),                            // 
    .CLKOUT (i_pll2_CLKOUT_w)                            // 
  );

temp-sense-gen i_temp_sense2
  (
    .PCLK (i_fasoc_m0mcu2_ext_HCLK_w),                            // 
    .PRESETn (i_fasoc_m0mcu2_ext_HRESETn_w),                            // 
    .PSEL (u_apb_slave_mux2_PSEL6_w),                            // 
    .PADDR (i_temp_sense2_PADDR_w),                            // 
    .PENABLE (u_ahb_to_apb2_PENABLE_w),                            // 
    .PWRITE (u_ahb_to_apb2_PWRITE_w),                            // 
    .PWDATA (u_ahb_to_apb2_PWDATA_w[31:0]),                            // 
    .PRDATA (i_temp_sense2_PRDATA_w),                            // 
    .PREADY (i_temp_sense2_PREADY_w),                            // 
    .PSLVERR (i_temp_sense2_PSLVERR_w)                            // 
  );

cmsdk_apb_slave_mux_rtl u_apb_slave_mux2
  (
    .DECODE4BIT (),
    .PSEL (u_ahb_to_apb2_PSEL_w),                            // 
    .PSEL0 (),
    .PREADY0 (1'h1),                            // 
    .PRDATA0 (32'h0),                            // 
    .PSLVERR0 (1'h0),                            // 
    .PSEL1 (),
    .PREADY1 (1'h1),                            // 
    .PRDATA1 (32'h0),                            // 
    .PSLVERR1 (1'h0),                            // 
    .PSEL2 (),
    .PREADY2 (1'h1),                            // 
    .PRDATA2 (32'h0),                            // 
    .PSLVERR2 (1'h0),                            // 
    .PSEL3 (),
    .PREADY3 (1'h1),                            // 
    .PRDATA3 (32'h0),                            // 
    .PSLVERR3 (1'h0),                            // 
    .PSEL4 (u_apb_slave_mux2_PSEL4_w),                            // 
    .PREADY4 (i_mem2_pready_w),                            // 
    .PRDATA4 (i_mem2_prdata_w[31:0]),                            // 
    .PSLVERR4 (i_mem2_pslverr_w),                            // 
    .PSEL5 (u_apb_slave_mux2_PSEL5_w),                            // 
    .PREADY5 (i_pll2_PREADY_w),                            // 
    .PRDATA5 (i_pll2_PRDATA_w[31:0]),                            // 
    .PSLVERR5 (i_pll2_PSLVERR_w),                            // 
    .PSEL6 (u_apb_slave_mux2_PSEL6_w),                            // 
    .PREADY6 (i_temp_sense2_PREADY_w),                            // 
    .PRDATA6 (i_temp_sense2_PRDATA_w[31:0]),                            // 
    .PSLVERR6 (i_temp_sense2_PSLVERR_w),                            // 
    .PSEL7 (),
    .PREADY7 (1'h1),                            // 
    .PRDATA7 (32'h0),                            // 
    .PSLVERR7 (1'h0),                            // 
    .PSEL8 (),
    .PREADY8 (1'h1),                            // 
    .PRDATA8 (32'h0),                            // 
    .PSLVERR8 (1'h0),                            // 
    .PSEL9 (),
    .PREADY9 (1'h1),                            // 
    .PRDATA9 (32'h0),                            // 
    .PSLVERR9 (1'h0),                            // 
    .PSEL10 (),
    .PREADY10 (1'h1),                            // 
    .PRDATA10 (32'h0),                            // 
    .PSLVERR10 (1'h0),                            // 
    .PSEL11 (),
    .PREADY11 (1'h1),                            // 
    .PRDATA11 (32'h0),                            // 
    .PSLVERR11 (1'h0),                            // 
    .PSEL12 (),
    .PREADY12 (1'h1),                            // 
    .PRDATA12 (32'h0),                            // 
    .PSLVERR12 (1'h0),                            // 
    .PSEL13 (),
    .PREADY13 (1'h1),                            // 
    .PRDATA13 (32'h0),                            // 
    .PSLVERR13 (1'h0),                            // 
    .PSEL14 (),
    .PREADY14 (1'h1),                            // 
    .PRDATA14 (32'h0),                            // 
    .PSLVERR14 (1'h0),                            // 
    .PSEL15 (),
    .PREADY15 (1'h1),                            // 
    .PRDATA15 (32'h0),                            // 
    .PSLVERR15 (1'h0),                            // 
    .PREADY (u_apb_slave_mux2_PREADY_w),                            // 
    .PRDATA (u_apb_slave_mux2_PRDATA_w),                            // 
    .PSLVERR (u_apb_slave_mux2_PSLVERR_w)                            // 
  );

cmsdk_ahb_to_apb_rtl u_ahb_to_apb2
  (
    .HCLK (i_fasoc_m0mcu2_ext_HCLK_w),                            // 
    .HBURST (i_fasoc_m0mcu2_ext_HBURST_w),                            // 
    .HRESETn (i_fasoc_m0mcu2_ext_HRESETn_w),                            // 
    .PCLKEN (i_fasoc_m0mcu2_PCLKEN_w),                            // 
    .HSEL (1'h1),                            // 
    .HADDR (i_fasoc_m0mcu2_ext_HADDR_w[15:0]),                            // 
    .HTRANS (i_fasoc_m0mcu2_ext_HTRANS_w[1:0]),                            // 
    .HSIZE (i_fasoc_m0mcu2_ext_HSIZE_w[2:0]),                            // 
    .HPROT (i_fasoc_m0mcu2_ext_HPROT_w[3:0]),                            // 
    .HWRITE (i_fasoc_m0mcu2_ext_HWRITE_w),                            // 
    .HREADY (i_fasoc_m0mcu2_ext_HREADY_w),                            // 
    .HWDATA (i_fasoc_m0mcu2_ext_HWDATA_w[31:0]),                            // 
    .HREADYOUT (),
    .HRDATA (u_ahb_to_apb2_HRDATA_w),                            // 
    .HRESP (u_ahb_to_apb2_HRESP_w),                            // 
    .PADDR (u_ahb_to_apb2_PADDR_w),                            // 
    .PENABLE (u_ahb_to_apb2_PENABLE_w),                            // 
    .PWRITE (u_ahb_to_apb2_PWRITE_w),                            // 
    .PSTRB (),
    .PPROT (),
    .PWDATA (u_ahb_to_apb2_PWDATA_w),                            // 
    .PSEL (u_ahb_to_apb2_PSEL_w),                            // 
    .APBACTIVE (u_ahb_to_apb2_APBACTIVE_w),                            // 
    .PRDATA (u_apb_slave_mux2_PRDATA_w[31:0]),                            // 
    .PREADY (u_apb_slave_mux2_PREADY_w),                            // 
    .PSLVERR (u_apb_slave_mux2_PSLVERR_w)                            // 
  );

fasoc_m0mcu_rtl i_fasoc_m0mcu2
  (
    .XTAL1 (_XTAL1_w),                            // 
    .XTAL2 (i_fasoc_m0mcu2_XTAL2_w),                            // 
    .NRST (),
    .P0 ({P0[15:0]}),                            // 
    .P1 ({P1[15:0]}),                            // 
    .nTRST (_nTRST_w),                            // 
    .TDI (),
    .TDO (),
    .SWDIOTMS ({SWDIOTMS}),                            // 
    .SWCLKTCK (_SWCLKTCK_w),                            // 
    .ext_HCLK (),
    .ext_HBURST (i_fasoc_m0mcu2_ext_HBURST_w),                            // 
    .ext_HRESETn (),
    .ext_HADDR (i_fasoc_m0mcu2_ext_HADDR_w),                            // 
    .ext_HTRANS (i_fasoc_m0mcu2_ext_HTRANS_w),                            // 
    .ext_HWRITE (i_fasoc_m0mcu2_ext_HWRITE_w),                            // 
    .ext_HSIZE (i_fasoc_m0mcu2_ext_HSIZE_w),                            // 
    .ext_HPROT (i_fasoc_m0mcu2_ext_HPROT_w),                            // 
    .ext_HREADY (i_fasoc_m0mcu2_ext_HREADY_w),                            // 
    .ext_HWDATA (i_fasoc_m0mcu2_ext_HWDATA_w),                            // 
    .ext_HRDATA (u_ahb_to_apb2_HRDATA_w[31:0]),                            // 
    .ext_HRESP (u_ahb_to_apb2_HRESP_w),                            // 
    .PRESETn (),
    .PCLK (),
    .PCLKG (),
    .APBACTIVE (u_ahb_to_apb2_APBACTIVE_w),                            // 
    .PCLKEN (i_fasoc_m0mcu2_PCLKEN_w)                            // 
  );

assign _XTAL1_w = XTAL1;
assign _nTRST_w = nTRST;
assign _SWCLKTCK_w = SWCLKTCK;
assign _SYSRESETN_w = SYSRESETN;
assign XTAL2 = _XTAL2_w;
assign _XTAL2_w = i_fasoc_m0mcu2_XTAL2_w;
assign SYSCLKOUT = _SYSCLKOUT_w;
assign _SYSCLKOUT_w = i_pll2_CLKOUT_w;
assign SYSCLK = _SYSCLK_w;
assign _SYSCLK_w = i_fasoc_m0mcu2_PCLK_w;
assign _SYSCLK_w = i_fasoc_m0mcu2_ext_HCLK_w;
assign i_pll2_PADDR_w[11:2] = u_ahb_to_apb2_PADDR_w[11:2];
assign i_temp_sense2_PADDR_w[3:2] = u_ahb_to_apb2_PADDR_w[3:2];


endmodule
