move:
	../../soc/python/hierarchy.py --source_file ./cmsdk_fasoc_apb_subsystem.v --module_name cmsdk_apb_slave_mux --dest_file ./cmsdk_mcu.v --module_file cmsdk_apb_slave_mux.v --hierarchy_file ./hierarchy.txt
check:
	../../soc/python/hierarchy_checker.py --list ./hierarchy_check.txt