ldo:
	../../soc/python/soc.py --design ./design_ldo.json --platform gf12lp --mode verilog --database add --generator_config ../../config/generator_config_12.json --filelist ./file_list_12.tcl --synthesis_req False --socrates_req False
clean_ldo:
	../../soc/python/clean.py --design ./design_ldo.json --platform gf12lp --connection remove --synthesis do_not_remove