soc:
	../../../soc/python/soc.py --design ./design2.json --mode verilog
soc_macro:
	../../../soc/python/soc.py --design ./design2.json --mode macro
soc_full:
	../../../soc/python/soc.py --design ./design2.json --mode full
