soc:
	../../../soc/python/soc.py --design ./design2.json --mode verilog --database add
soc_macro:
	../../../soc/python/soc.py --design ./design2.json --mode macro --database add
soc_full:
	../../../soc/python/soc.py --design ./design2.json --mode full --database add
