test0:
	./soc.py --design ../../test/resolved_design0.json

test:
	./soc.py --design ../../test/resolved_design.json

soc:
	python ./python/soc.py --design /afs/eecs.umich.edu/vlsida/projects/FASoC/TSMC_65LP/fasoc/soc/test/design2.json
