model:
	../../soc/python/power_area_estimator/wrapper.py --mode ml_regression --generator ldo-gen --constraint area
evaluate:
	../../soc/python/power_area_estimator/wrapper.py --mode model_evaluator --generator pll-gen --constraint area